### ISSUE TITLE
Milestone 2 checklist

### ISSUE THREAD

**Issue by williamxu7** [UBC-MDS/DSCI_525_Group13_Rainfall#30]
- [x] Setup your EC2 instance with JupyterHub.
- [x] Install all necessary things needed in your UNIX server (amazon ec2 instance).
- [x] Setup your S3 bucket.
- [x] Move the data that you wrangled in your last milestone to s3.
- [x] Get the data from S3 in your notebook and make data ready for machine learning.
